# Generated by Django 5.0.6 on 2024-06-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ad_id', models.PositiveIntegerField(unique=True)),
                ('author', models.CharField(max_length=255)),
                ('views', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
