# Generated by Django 5.0.6 on 2024-06-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_id',
        ),
    ]
